######################################################################
#
# File name : encoder83_tb.udo
# Created on: Sat Oct 09 22:13:18 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
