######################################################################
#
# File name : encoder83_tb_wave.do
# Created on: Wed Oct 13 10:52:35 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
