######################################################################
#
# File name : encoder83_tb_simulate.do
# Created on: Wed Oct 13 10:52:35 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.encoder83_tb xil_defaultlib.glbl

do {encoder83_tb_wave.do}

view wave
view structure
view signals

do {encoder83_tb.udo}

run 1000ns
