######################################################################
#
# File name : logic_gates_2.udo
# Created on: Thu Sep 23 20:43:58 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
