######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Thu Sep 23 20:45:37 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
