######################################################################
#
# File name : entend_tb_simulate.do
# Created on: Sun Sep 26 11:37:46 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.entend_tb xil_defaultlib.glbl

do {entend_tb_wave.do}

view wave
view structure
view signals

do {entend_tb.udo}

run 1000ns
