######################################################################
#
# File name : entend_tb_wave.do
# Created on: Sun Sep 26 11:37:46 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
