######################################################################
#
# File name : FA_tb_compile.do
# Created on: Sun Jun 26 18:05:05 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.5-3.srcs/sources_1/new/FA.v" \
"../../../6.5-3.srcs/sources_1/new/FA_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

