######################################################################
#
# File name : decoder_tb_wave.do
# Created on: Wed Oct 13 11:00:44 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
