######################################################################
#
# File name : barrelshifter32_tb_wave.do
# Created on: Thu Oct 14 21:46:15 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
