######################################################################
#
# File name : barrelshifter32_tb_simulate.do
# Created on: Thu Oct 14 21:46:15 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.barrelshifter32_tb xil_defaultlib.glbl

do {barrelshifter32_tb_wave.do}

view wave
view structure
view signals

do {barrelshifter32_tb.udo}

run 1000ns
