######################################################################
#
# File name : three_state_gates_tb_wave.do
# Created on: Fri Oct 08 17:45:05 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
