######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Thu Sep 23 21:09:22 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
