######################################################################
#
# File name : Synchronous_D_FF_tb.udo
# Created on: Thu Oct 28 19:51:57 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
