######################################################################
#
# File name : Synchronous_D_FF.udo
# Created on: Thu Oct 28 19:50:22 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
