######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Thu Sep 23 19:46:10 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
