######################################################################
#
# File name : logic_gates_tb_compile.do
# Created on: Sun Sep 26 11:30:15 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.1-1.srcs/sources_1/new/logic_gates_1.v" \
"../../../6.1-1.srcs/sources_1/new/logic_gates_1_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

