######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Sun Sep 26 11:30:21 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
