######################################################################
#
# File name : pcreg_tb_wave.do
# Created on: Thu Oct 28 23:15:15 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
