######################################################################
#
# File name : pcreg_tb.udo
# Created on: Thu Oct 28 22:53:22 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
