######################################################################
#
# File name : DataCompare4_tb_wave.do
# Created on: Thu Oct 21 21:30:34 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
