######################################################################
#
# File name : encoder83_Pri_tb.udo
# Created on: Tue Oct 12 21:30:20 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
