######################################################################
#
# File name : encoder83_Pri_tb_wave.do
# Created on: Wed Oct 13 11:11:46 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
