######################################################################
#
# File name : de_selector14_tb_simulate.do
# Created on: Fri Oct 08 23:40:36 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.de_selector14_tb xil_defaultlib.glbl

do {de_selector14_tb_wave.do}

view wave
view structure
view signals

do {de_selector14_tb.udo}

run 1000ns
