######################################################################
#
# File name : de_selector14_tb_wave.do
# Created on: Fri Oct 08 23:40:36 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
