######################################################################
#
# File name : transmission8_tb_wave.do
# Created on: Fri Oct 08 23:41:55 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
