######################################################################
#
# File name : transmission8_tb.udo
# Created on: Fri Oct 08 21:22:41 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
