######################################################################
#
# File name : Adder_tb_wave.do
# Created on: Fri Oct 22 00:54:59 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
