######################################################################
#
# File name : Adder_tb.udo
# Created on: Fri Oct 22 00:54:45 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
