######################################################################
#
# File name : display7_tb.udo
# Created on: Sat Oct 09 21:28:59 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
