######################################################################
#
# File name : Asynchronous_D_FF_tb_wave.do
# Created on: Thu Oct 28 23:17:37 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
