######################################################################
#
# File name : DataCompare8_tb_wave.do
# Created on: Thu Oct 21 21:55:25 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
