######################################################################
#
# File name : JK_FF_tb_compile.do
# Created on: Thu Oct 28 23:16:14 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.6-3.srcs/sources_1/new/JK_FF.v" \
"../../../6.6-3.srcs/sources_1/new/JK_FF_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

