######################################################################
#
# File name : JK_FF_tb.udo
# Created on: Thu Oct 28 20:58:26 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
