######################################################################
#
# File name : JK_FF_tb_wave.do
# Created on: Thu Oct 28 23:16:18 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
